### ISSUE TITLE
Support to cancel the execution of a command

### ISSUE THREAD

**Issue by pchico83** [docker/extensions-sdk#123]
I am running a long-running command from the exec SDK, and my extension should allow the users to cancel the execution at any time. This is not supported at the moment

**Comment by gtardif** [comment]
Hi, long running commands [started with streaming options](https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/Exec/#exec-1)return an object allowing you to close the long running process (since SDK 0.2.3). 
Note also that when users exit the extension tab, these processes will be closed automatically.
