### ISSUE TITLE
Provide a new `com.docker.extension.icon-url` label in Dockerfile

### ISSUE THREAD

**Issue by Dentrax** [docker/extensions-sdk#191]
It would be nice to provide a new label: 

```dockerfile
LABEL com.docker.extension.icon-url=""
```

That's because the icons we use in the extension have some licensing, for example: _If you want to use this icon in your project, you have to mention the URL._

**Comment by felipecruz91** [comment]
Hi @Dentrax, do you refer to the icon that is displayed in the Extensions Marketplace?

If so, at the moment we just provide the label `com.docker.desktop.extension.icon` to display the icon in the Marketplace.

If you are required to cite, acknowledge or give credit because of the use of an asset in your extension, you could perhaps use the `com.docker.extension.detailed-description` or `com.docker.extension.additional-urls`. See [extension image labels](https://docs.docker.com/desktop/extensions-sdk/extensions/labels/) for more details.

If that is not an option, please elaborate a bit more to better understand your use case.

**Comment by Dentrax** [comment]
> Do you refer to the icon that is displayed in the Extensions Marketplace?

Correct.

> If you are required to cite, acknowledge or give credit...

Yes, that's what I want to do. I think `com.docker.extension.detailed-description` might be a great fit for this. Thanks!

Closig.
