### ISSUE TITLE
ux: simplify some Makefile commands: remove `-extension` suffix

### ISSUE THREAD

**Issue by Dentrax** [docker/extensions-sdk#192]
I think it's not necessary to mention `-extension` suffix in all `make` commands. We can simplify the as follows:

```diff
- build-extension
+ build
- install-extension
+ install
- prepare-extension
+ prepare
- push-extension
+ push
- update-extension
+ update
```

**Comment by felipecruz91** [comment]
Hi @Dentrax, thanks for the suggestion. I'll pass it along to the team and we'll get back to you once we have a resolution.

**Comment by benja-M-1** [comment]
Hi @Dentrax for the moment we decided to not change this because having it is more a matter of taste. If we do c-the change it is likely that others will want to have `-extension`. 
Furthermore, it is a fairly simple change to do in the generate makefile so we prefer not to change that for now.
However, if there are more votes for removing the suffix then we will reconsider this!
