### ISSUE TITLE
Unable to use @docker/extension-api-client in reactjs project

### ISSUE THREAD

**Issue by jatin711-debug** [docker/extensions-sdk#222]
**Describe the bug**
Unable to use @docker/extension-api-client in project
Error am Getting:
```
index.js:5 Uncaught Error: This version of @docker/extension-api-client is not supported by your version of Docker Desktop. Please upgrade to the latest version
```

**Output of `docker extension version`:**

```
Client Version: v0.2.9
Server API Version: 0.2.3
```

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional context**

**Comment by jatin711-debug** [comment]
Hi @benja-M-1 , I just setup a fresh react - typescript application using vite and did:
```
npm i @docker/extension-api-client
```
Imported and used in App.js file, which looks like: 
```
import { createDockerDesktopClient } from '@docker/extension-api-client';

function App() {
  const client = createDockerDesktopClient()
  console.log(client.docker.cli.exec("docker",["images"]))
  return (
    "hello"
  )
}

export default App
```

**Comment by benja-M-1** [comment]
Just to be 100% sure, are you seeing this error in the dev tools of a browser or in Docker Desktop dev tools for your extension?
Since you don't mention any installation steps I have a doubt. If it is the former, extensions are not supposed to run out of Docker Desktop, they won't work in a browser because the extension SDK won't be provided even if you have imported it.

Also, I encourage you to use the cli to generate an extension: `docker extension init`. For the moment, it creates a Create React App template, but you can easily convert it to a Vite one.
